kind = "mobile"
previewPath = "/mobile/"
title = "CodeLearn AI (App)"
version = "1.0.0"
id = "artifacts/codelearn"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 23318

[services.development]
run = "pnpm --filter @workspace/codelearn run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/codelearn", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/codelearn", "run", "serve" ]

[services.env]
PORT = "23318"
BASE_PATH = "/mobile/"
